config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update]

  resources :events do
    post 'add_user', on: :member
  end

  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_paranoid # Enables soft deletion
  
  has_many :registrations, dependent: :destroy
  has_many :attendees, through: :registrations, source: :user
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'

  validates :name, :description, :date, :location, :capacity, presence: true
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :registrations, dependent: :destroy
  has_many :attended_events, through: :registrations, source: :event
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id', dependent: :destroy

  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :check_creator, only: [:edit, :update, :destroy]

  def index
    @created_events = current_user.created_events
    @attended_events = current_user.attended_events.where.not(id: @created_events.pluck(:id))
    @events = @created_events + @attended_events
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)
    @event.creator_id = current_user.id
    if @event.save
      # Create a registration linking the current user to the event
      Registration.create(user: current_user, event: @event)
  
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: 'Event was successfully destroyed.'
  end


  # Custom action to add a user to the event
  def add_user
    @event = Event.find_by(id: params[:event_id])
    @user = User.find_by(id: params[:user_id])
  
    puts "Event ID: #{params[:event_id]}"
    puts "User ID: #{params[:user_id]}"
    
    unless @event && @user
      flash[:alert] = 'Event or user not found.'
      redirect_to events_path
      return
    end
  
    if @event.attendees.exclude?(@user)
      @event.attendees << @user
      flash[:notice] = 'User successfully added to the event.'
    else
      flash[:alert] = 'User is already registered for this event.'
    end
  
    redirect_to event_path(@event)
  end
  
  
  

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description, :date, :location, :capacity)
    end

    def check_creator
      unless @event.creator_id == current_user.id
        redirect_to events_path, alert: 'You do not have permission to perform this action.'
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    before_action :set_event
    before_action :authenticate_user!
  
    # POST /events/:event_id/registrations
    def create
      @user = current_user
  
      if @event.attendees.include?(@user)
        flash[:alert] = 'You are already registered for this event.'
      else
        @event.attendees << @user
        flash[:notice] = 'Successfully registered for the event.'
      end
  
      redirect_to event_path(@event)
    end
  
    # DELETE /events/:event_id/registrations/:id
    def destroy
      @user = User.find(params[:id])
  
      if @event.attendees.include?(@user)
        @event.attendees.delete(@user)
        flash[:notice] = 'Successfully unregistered from the event.'
      else
        flash[:alert] = 'User is not registered for this event.'
      end
  
      redirect_to event_path(@event)
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:event_id])
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    def show
      @user = current_user
    end
  
    def edit
      @user = current_user
    end
  
    def update
      @user = current_user
      if @user.update(user_params)
        redirect_to user_path(@user), notice: 'Profile updated successfully.'
      else
        render :edit
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:email, :age, :gender, :description)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_local_field :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Event' %>
  </div>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>My Events</h1>

<%= link_to 'New Event', new_event_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Date</th>
      <th>Location</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.capacity %></td>
        <td><%= link_to 'Show', event %></td>
        <% if event.creator_id == current_user.id %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @event.capacity %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
<% if @event.creator_id == current_user.id %>
  <%= link_to "Destroy", @event, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>

<h2>Attendees:</h2>
<% @attendees.each do |attendee| %>
  <p><%= attendee.email %></p>
<% end %>

<% if @event.creator_id == current_user.id %>
  <%= form_with(url: add_user_event_path(@event), method: :post) do |form| %>
    <%= form.hidden_field :event_id, value: @event.id %>
    <%= form.collection_select :user_id, User.all, :id, :email %>
    <%= form.submit 'Add User' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventsApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'My Events', events_path %></li>
            <li><%= link_to 'New Event', new_event_path %></li>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <!-- Footer content -->
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.select :gender, options_for_select(['Male', 'Female', 'Other'], @user.gender) %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Profile' %>
  </div>
<% end %>

<%= link_to 'Back', user_path(@user) %>

app/views/users/show.html.erb
<h1>Profile</h1>

<p><strong>Email:</strong> <%= @user.email %></p>
<p><strong>Age:</strong> <%= @user.age %></p>
<p><strong>Gender:</strong> <%= @user.gender %></p>
<p><strong>Description:</strong> <%= @user.description %></p>

<%= link_to 'Edit Profile', edit_user_path(@user) %>